# Generated by Django 6.0 on 2026-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('finished', 'Завершена'), ('canceled', 'Скасована')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
