# Generated by Django 6.0 on 2025-12-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('price_per_day', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
